=== s6mike/argview/mapjs/public/schemas/mapjs-json.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "http://argview.org/schemas/mapjs-json.json",
  "type": "object",
  "additionalProperties": false,
  "default": {},
  "title": "mapjs json schema",
  "description": "mapjs file",
  "required": [
    "formatVersion",
    "title",
    "id",
    "ideas"
  ],
  "$defs": {
    "ideas": {
      "type": "object",
      "additionalProperties": false,
      "default": {},
      "title": "The ideas Schema",
      "patternProperties": {
        "$comment": "Should this just be any string?",
        "^-?[1-9]*[0-9](.[0-9]+)?$": {
          "$ref": "#/$defs/node"
        },
        "uniqueItems": true
      }
    },
    "node": {
        "type": "object",
        "additionalProperties": false,
        "default": {},
        "title": "idea node Schema",
        "required": [
          "title",
          "id"
        ],
        "properties": {
          "id": {
            "$comment": "Should type be string only?",
            "type": [
              "string",
              "integer"
            ],
            "default": "",
            "title": "The id Schema",
            "examples": [
              "1"
            ]
          },
          "title": {
            "type": "string",
            "default": "",
            "title": "The title Schema",
            "examples": [
              "All swans are white.",
              "group"
            ]
          },
          "attr": {
            "type": "object",
            "additionalProperties": false,
            "default": {},
            "title": "The attr Schema",
            "properties": {
              "group": {
                "type": "string",
                "default": "supporting",
                "title": "The group Schema",
                "examples": [
                  "supporting",
                  "opposing"
                ]
              },
              "contentLocked": {
                "type": [
                  "string",
                  "boolean"
                ],
                "default": "",
                "title": "The contentLocked Schema",
                "examples": [
                  "true",
                  true
                ]
              },
              "note": {
                "type": "object",
                "additionalProperties": false,
                "title": "The note Schema",
                "properties": {
                  "index": {
                    "type": "integer",
                    "default": 0,
                    "title": "The index Schema",
                    "examples": [
                      22
                    ]
                  },
                  "text": {
                    "type": "string",
                    "default": "",
                    "title": "The text Schema",
                    "examples": [
                      "Observing individuals doesn't prove anything about the whole population."
                    ]
                  }
                },
                "default": {
                  "index": 0,
                  "text": ""
                },
                "examples": [
                  {
                    "index": 22,
                    "text": "Observing individuals doesn't prove anything about the whole population."
                  }
                ]
              },
              "style": {},
              "parentConnector": {
                "type": "object",
                "additionalProperties": false,
                "default": {
                  "arrow": "both",
                  "width": 3,
                  "label": "+"
                },
                "title": "The parentConnector Schema",
                "properties": {
                  "arrow": {
                    "type": "string",
                    "default": "both",
                    "title": "The arrow Schema",
                    "examples": [
                      "both"
                    ]
                  },
                  "lineStyle": {
                    "type": "string",
                    "default": "",
                    "title": "The lineStyle Schema",
                    "examples": [
                      "dashed"
                    ]
                  },
                  "color": {
                    "type": "string",
                    "default": "#000000",
                    "title": "The color Schema",
                    "examples": [
                      "#ff0000"
                    ]
                  },
                  "width": {
                    "type": "integer",
                    "default": 3,
                    "title": "The width Schema",
                    "examples": [
                      5
                    ]
                  },
                  "label": {
                    "type": "string",
                    "default": "+",
                    "title": "The label Schema",
                    "examples": [
                      "rejects (X)"
                    ]
                  }
                },
                "examples": [
                  {
                    "arrow": "both",
                    "width": 5,
                    "label": "rejects (X)"
                  }
                ]
              },
              "styleNames": {
                "type": "array",
                "items": {
                  "type": "string"
                },
                "default": [],
                "title": "The styleNames Schema",
                "examples": [
                  [
                    "attr_implicit_claim"
                  ]
                ]
              },
              "position": {
                "type": "array",
                "items": {
                  "type": "number"
                },
                "minItems": 3,
                "maxItems": 3,
                "default": [
                  0,
                  0,
                  0
                ],
                "title": "The position Schema",
                "examples": [
                  [
                    -216,
                    -153,
                    1
                  ]
                ]
              },
              "collapsed": "boolean",
              "attachment": {
                "type": "object",
                "additionalProperties": false,
                "default": {},
                "title": "The attachment Schema",
                "required": [
                  "contentType",
                  "content"
                ],
                "properties": {
                  "contentType": "string",
                  "content": "string"
                }
              },
              "icon": {
                "type": "object",
                "additionalProperties": false,
                "default": {},
                "title": "The icon Schema",
                "required": [
                  "url",
                  "width",
                  "height",
                  "position"
                ],
                "properties": {
                  "url": {
                    "type": "string",
                    "default": "",
                    "title": "The url Schema",
                    "examples": [
                      "data:image/png;base64,iVB"
                    ]
                  },
                  "width": {
                    "type": "integer",
                    "default": 0,
                    "title": "The width Schema",
                    "examples": [
                      96
                    ]
                  },
                  "height": {
                    "type": "integer",
                    "default": 0,
                    "title": "The height Schema",
                    "examples": [
                      96
                    ]
                  },
                  "position": {
                    "type": "string",
                    "default": "",
                    "title": "The position Schema",
                    "examples": [
                      "top"
                    ]
                  }
                },
                "examples": [
                  {
                    "url": "data:image/png;base64,iVBORw0K",
                    "width": 96,
                    "height": 96,
                    "position": "top",
                    "group": "opposing",
                    "contentLocked": "true"
                  }
                ]
              }
            }
          },
          "ideas": {
            "$ref": "#/$defs/ideas"
          }
        },
        "examples": [
          {
            "1": {
              "title": "Not all swans are white.",
              "id": "3"
            }
          },
          {
            "title": "group",
            "ideas": {
              "1": {
                "title": "Not all swans are white.",
                "id": "3"
              }
            },
            "id": "2",
            "attr": {
              "group": "opposing",
              "contentLocked": "true"
            }
          }
        ]
    },
    "status": {
      "title": "The status Schema",
      "required": [
        "description",
        "icon"
      ],
      "properties": {
        "description": {
          "type": "string",
          "default": "",
          "title": "The description Schema",
          "examples": [
            "Not Started"
          ]
        },
        "priority": {
          "type": "integer",
          "default": 0,
          "title": "The priority Schema",
          "examples": [
            1
          ]
        },
        "icon": {
          "type": "object",
          "additionalProperties": false,
          "default": {},
          "title": "The icon Schema",
          "required": [
            "height",
            "width",
            "position",
            "url"
          ],
          "properties": {
            "height": {
              "type": "integer",
              "default": 0,
              "title": "The height Schema",
              "examples": [
                25
              ]
            },
            "width": {
              "type": "integer",
              "default": 0,
              "title": "The width Schema",
              "examples": [
                25
              ]
            },
            "position": {
              "type": "string",
              "default": "",
              "title": "The position Schema",
              "examples": [
                "left"
              ]
            },
            "url": {
              "type": "string",
              "default": "",
              "title": "The url Schema",
              "examples": [
                "/assets/progress/testing/flat/not-started.png"
              ]
            }
          }
        }
      }
    }
  },
  "properties": {
    "$schema": {
      "type": "string",
      "default": "https://argview.org/schemas/mapjs-json.json",
      "title": "The $schema Schema",
      "examples": [
        "https://argview.org/schemas/mapjs-json.json"
      ]
    },
    "title": {
      "type": "string",
      "default": "",
      "title": "The title Schema",
      "examples": [
        "All swans are white.",
        ""
      ]
    },
    "id": {
      "type": "string",
      "default": "root",
      "title": "The id Schema",
      "examples": [
        "root"
      ]
    },
    "attr": {
      "type": "object",
      "additionalProperties": false,
      "default": {},
      "title": "The attr Schema",
      "properties": {
        "theme": {
          "type": "string",
          "default": "",
          "title": "The theme Schema",
          "examples": [
            "argMappingSimple"
          ]
        },
        "progress-statuses": {
          "type": "object",
          "additionalProperties": false,
          "default": {},
          "title": "The progress-statuses Schema",
          "properties": {
            "not-started": {
              "$ref": "#/$defs/status"
            },
            "passing": {
              "$ref": "#/$defs/status"
            },
            "in-progress": {
              "$ref": "#/$defs/status"
            },
            "failure": {
              "$ref": "#/$defs/status"
            }
          }
        }
      },
      "examples": [
        {
          "theme": "argMappingSimple"
        }
      ]
    },
    "ideas": {
      "$ref": "#/$defs/ideas"
    },
    "theme": {
      "$ref": "./mapjs-json-theme.json"
    },
    "formatVersion": {
      "type": "integer",
      "default": 3,
      "title": "The formatVersion Schema",
      "examples": [
        3
      ]
    },
    "links": {
      "type": "array",
      "additionalProperties": false,
      "default": [],
      "title": "The links Schema",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "title": "A Schema",
        "required": [
          "ideaIdFrom",
          "ideaIdTo",
          "attr"
        ],
        "properties": {
          "ideaIdFrom": {
            "type": "string",
            "title": "The ideaIdFrom Schema",
            "examples": [
              "1"
            ]
          },
          "ideaIdTo": {
            "type": "string",
            "title": "The ideaIdTo Schema",
            "examples": [
              "5",
              "6"
            ]
          },
          "attr": {
            "type": "object",
            "additionalProperties": false,
            "title": "The attr Schema",
            "required": [
              "style"
            ],
            "properties": {
              "style": {
                "type": "object",
                "additionalProperties": false,
                "title": "The style Schema",
                "required": [
                  "color",
                  "lineStyle",
                  "arrow"
                ],
                "properties": {
                  "color": {
                    "type": "string",
                    "title": "The color Schema",
                    "examples": [
                      "red",
                      "blue"
                    ]
                  },
                  "lineStyle": {
                    "type": "string",
                    "title": "The lineStyle Schema",
                    "examples": [
                      "dashed",
                      "solid"
                    ]
                  },
                  "arrow": {
                    "type": [
                      "string",
                      "boolean"
                    ],
                    "title": "The arrow Schema",
                    "examples": [
                      "to",
                      "both",
                      false
                    ]
                  }
                },
                "examples": [
                  {
                    "color": "red",
                    "lineStyle": "dashed",
                    "arrow": "to"
                  },
                  {
                    "color": "blue",
                    "lineStyle": "solid",
                    "arrow": "to"
                  }
                ]
              }
            },
            "examples": [
              {
                "style": {
                  "color": "red",
                  "lineStyle": "dashed",
                  "arrow": "to"
                }
              },
              {
                "style": {
                  "color": "blue",
                  "lineStyle": "solid",
                  "arrow": "to"
                }
              }
            ]
          }
        },
        "examples": [
          {
            "ideaIdFrom": "1",
            "ideaIdTo": "5",
            "attr": {
              "style": {
                "color": "red",
                "lineStyle": "dashed",
                "arrow": "to"
              }
            }
          },
          {
            "ideaIdFrom": "1",
            "ideaIdTo": "6",
            "attr": {
              "style": {
                "color": "blue",
                "lineStyle": "solid",
                "arrow": "to"
              }
            }
          }
        ]
      },
      "examples": [
        [
          {
            "ideaIdFrom": "1",
            "ideaIdTo": "5",
            "attr": {
              "style": {
                "color": "red",
                "lineStyle": "dashed",
                "arrow": "to"
              }
            }
          },
          {
            "ideaIdFrom": "1",
            "ideaIdTo": "6",
            "attr": {
              "style": {
                "color": "blue",
                "lineStyle": "solid",
                "arrow": "to"
              }
            }
          }
        ]
      ]
    },
    "original_root_node_title": {
      "type": "string",
      "default": "",
      "title": "The original_root_node_title Schema",
      "description": "Added when the file is first loaded locally, to link online changes to original file. This is the original name of the topmost root in the argument map. Used to create `map_id`.",
      "examples": [
        "All swans are white."
      ]
    },
    "map_id": {
      "type": "string",
      "minLength": 18,
      "maxLength": 18,
      "default": "",
      "title": "The map_id Schema",
      "description": "Added when the file is first saved online to link online changes to original file. Created from the first 10 characters of a SHA256 hash of `original_root_node_title`.",
      "examples": [
        "mapjson_45f3c10ad7"
      ]
    },
    "original_upload_time": {
      "type": "string",
      "format": "date-time",
      "minLength": 24,
      "maxLength": 24,
      "default": "",
      "title": "The original_upload_time Schema",
      "description": "Added when the file is first saved online, to help with de-duplicating hash collisions.",
      "examples": [
        "2023-12-16T16:22:40.221Z"
      ]
    }
  },
  "examples": [
    {
      "title": "All swans are white.",
      "id": "root",
      "attr": {
        "theme": "argMappingSimple"
      },
      "ideas": {
        "1": {
          "title": "All swans are white.",
          "id": "1",
          "ideas": {
            "1": {
              "title": "group",
              "ideas": {
                "1": {
                  "title": "Not all swans are white.",
                  "id": "3"
                }
              },
              "id": "2",
              "attr": {
                "group": "opposing",
                "contentLocked": "true"
              }
            },
            "2": {
              "title": "group",
              "ideas": {
                "1": {
                  "title": "These swans are representative of all swans.",
                  "id": "5"
                },
                "2": {
                  "title": "Every swan I’ve ever seen is white.",
                  "id": "6"
                }
              },
              "id": "4",
              "attr": {
                "group": "supporting",
                "contentLocked": "true"
              }
            }
          }
        }
      },
      "theme": {
        "example_theme": "stuff"
      },
      "formatVersion": 3,
      "links": [
        {
          "ideaIdFrom": "1",
          "ideaIdTo": "5",
          "attr": {
            "style": {
              "color": "red",
              "lineStyle": "dashed",
              "arrow": "to"
            }
          }
        },
        {
          "ideaIdFrom": "1",
          "ideaIdTo": "6",
          "attr": {
            "style": {
              "color": "blue",
              "lineStyle": "solid",
              "arrow": "to"
            }
          }
        }
      ]
    }
  ]
}

=== s6mike/argview/test/input/mapjs-json/example1-simple-replicated-in-mapjs-legacy.json
{
  "$schema": "../../schemas/mapjs-json.json",
  "id": "root",
  "formatVersion": 3,
  "ideas": {
    "4": {
      "title": "Map 2: All swans are white.",
      "id": 24,
      "attr": {
        "position": [
          -87,
          -123.99999618530273,
          1
        ]
      },
      "ideas": {
        "1": {
          "title": "group",
          "id": 27,
          "attr": {
            "contentLocked": true,
            "group": "supporting"
          },
          "ideas": {
            "1": {
              "title": "Every swan Iâ€™ve ever seen is white.",
              "id": 28
            },
            "2": {
              "title": "These swans are representative of all swans.",
              "id": 29
            }
          }
        },
        "-1": {
          "title": "group",
          "id": 32,
          "attr": {
            "contentLocked": true,
            "group": "opposing"
          },
          "ideas": {
            "1": {
              "title": "Not all swans are white.",
              "id": 33
            }
          }
        }
      }
    }
  },
  "attr": {},
  "title": "text options",
  "links": []
}
